# Generated by Django 6.0.2 on 2026-03-11 18:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alt', models.CharField(max_length=255, null=True)),
                ('caption', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('thumbnail_u_r_l', models.CharField(max_length=255, null=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('mime_type', models.CharField(max_length=255, null=True)),
                ('filesize', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('width', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('height', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('focal_x', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('focal_y', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_thumbnail_url', models.CharField(max_length=255, null=True)),
                ('sizes_thumbnail_width', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_thumbnail_height', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_thumbnail_mime_type', models.CharField(max_length=255, null=True)),
                ('sizes_thumbnail_filesize', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('sizes_thumbnail_filename', models.CharField(max_length=255, null=True)),
                ('sizes_square_url', models.CharField(max_length=255, null=True)),
                ('sizes_square_width', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_square_height', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_square_mime_type', models.CharField(max_length=255, null=True)),
                ('sizes_square_filesize', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('sizes_square_filename', models.CharField(max_length=255, null=True)),
                ('sizes_small_url', models.CharField(max_length=255, null=True)),
                ('sizes_small_width', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_small_height', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_small_mime_type', models.CharField(max_length=255, null=True)),
                ('sizes_small_filesize', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('sizes_small_filename', models.CharField(max_length=255, null=True)),
                ('sizes_medium_url', models.CharField(max_length=255, null=True)),
                ('sizes_medium_width', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_medium_height', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_medium_mime_type', models.CharField(max_length=255, null=True)),
                ('sizes_medium_filesize', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('sizes_medium_filename', models.CharField(max_length=255, null=True)),
                ('sizes_large_url', models.CharField(max_length=255, null=True)),
                ('sizes_large_width', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_large_height', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_large_mime_type', models.CharField(max_length=255, null=True)),
                ('sizes_large_filesize', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('sizes_large_filename', models.CharField(max_length=255, null=True)),
                ('sizes_xlarge_url', models.CharField(max_length=255, null=True)),
                ('sizes_xlarge_width', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_xlarge_height', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_xlarge_mime_type', models.CharField(max_length=255, null=True)),
                ('sizes_xlarge_filesize', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('sizes_xlarge_filename', models.CharField(max_length=255, null=True)),
                ('sizes_og_url', models.CharField(max_length=255, null=True)),
                ('sizes_og_width', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_og_height', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('sizes_og_mime_type', models.CharField(max_length=255, null=True)),
                ('sizes_og_filesize', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('sizes_og_filename', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PayloadFolder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('folder_id', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payload_folders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.JSONField(null=True)),
                ('meta_title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.CharField(max_length=255, null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('generate_slug', models.BooleanField(default=True, null=True)),
                ('slug', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_status', blog.models.PostStatusField(default='draft', null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
    ]
