name: Update Static Files

on:
  push:
    branches: [main]
    paths:
        - 'src/static/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  upload-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: sa-east-1
          role-to-assume: arn:aws:iam::987608117561:role/ibiraWorkflow
        
      - name: Upload static files to S3
        run: aws s3 sync src/static/ s3://public-ibira/static/ --delete